### ISSUE TITLE
missing styling for banner below shedule

### ISSUE THREAD

**Issue by thilo** [coworkingfestival/coworkingfestival.github.io#25]
<img width="933" alt="screen shot 2018-09-07 at 13 59 05" src="https://user-images.githubusercontent.com/8471/45217946-3519d200-b2a6-11e8-823a-beadd4065a20.png">
its in the branch "banner" in the file schedule.html

**Comment by Kriesse** [comment]
Adjusted padding and background a bit, looks like in the screenshot below now.
Tried a full-width green background, but didn't look good. Maybe they can provide a plain color version of the banner, without the grass texture?
Anyway I think this is fine for now!

![image](https://user-images.githubusercontent.com/53684/45504921-7c62ff80-b78b-11e8-9254-aa3fc2bbd9cc.png)
