### ISSUE TITLE
favicon isn't showing

### ISSUE THREAD

**Issue by inthatdress** [coworkingfestival/coworkingfestival.github.io#3]
Favicon...the little image that's supposed to show up on the tab next to the page title instead of the white page icon that is there now.
<img width="672" alt="screen shot 2018-06-27 at 10 12 19 pm" src="https://user-images.githubusercontent.com/19808995/42009247-8057fd14-7a57-11e8-92bb-68a33634ad9b.png">
I've checked the links and I can't tell off hand why it isn't working. Do you know anything about these? Can we make Kristina a contributor so I can show/ask her?

Thanks!

**Comment by thilo** [comment]
odd, works for me in Firefox and Chrome
<img width="467" alt="screen shot 2018-06-29 at 13 58 47" src="https://user-images.githubusercontent.com/8471/42091192-9a9f0e62-7ba4-11e8-9faa-f28a8b994f4c.png">

**Comment by inthatdress** [comment]
It's working on my end now
