### ISSUE TITLE
icon is missing or wrong source path for calendar days in schedule

### ISSUE THREAD

**Issue by thilo** [coworkingfestival/coworkingfestival.github.io#8]
<img width="124" alt="screen shot 2018-07-19 at 21 56 29" src="https://user-images.githubusercontent.com/8471/42966850-a9f64b78-8b9e-11e8-90cf-fd56cedbfe1b.png">

applies to #9

**Comment by Kriesse** [comment]
@thilo Can you provide a screenshot with more context, or a link to the file where the icon is supposed to be? I'm not finding it.

**Comment by thilo** [comment]
@Kriesse on the schedule page: 
<img width="1184" alt="screen shot 2018-07-23 at 00 11 29" src="https://user-images.githubusercontent.com/8471/43050647-00ba8f76-8e0d-11e8-9e92-d43f9124e135.png">

**Comment by thilo** [comment]
@inthatdress the calendar is uncommented but you can run it locally to see the issue.

**Comment by inthatdress** [comment]
This needs to be included in the head of the page:
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet" type="text/css">

The icon is from font-awesome. I added this to the page in Chrome dev tools and the icons showed up.
